### ISSUE TITLE
Problem with packed

### ISSUE THREAD

**Issue by MythodeaLoL** [mervick/JavaScriptUnpacker#1]
i have this packed file, but i cant unpacker

```
Hidden Content
```

**Comment by MythodeaLoL** [comment]
This other script decode 90% of this code, but have a error, you can help me to fix it?
#https://github.com/rkaradas/php-javascript-unpacker/issues/1
@mervick

**Comment by mervick** [comment]
I just have copied your code above and then put it into a file `issue.packed.js`, after that:

``` php
$js = str_replace(["\r", "\n"], '', file_get_contents(__DIR__.'/issue.packed.js'));
echo JavaScriptUnpacker::unpack($js);
```

And it was unpacked!

**Comment by MythodeaLoL** [comment]
The way I was using was not working, I must have forgotten something.

You can hide the result? To keep the website make some changes =)

**Comment by mervick** [comment]
Already done
