### ISSUE TITLE
AADecode php

### ISSUE THREAD

**Issue by MythodeaLoL** [mervick/JavaScriptUnpacker#2]
Here's a script that would be interesting if it were in php.
Should you be interested.
<i>Sample JavaScript AADecode </i> 
http://cat-in-136.github.io/2010/12/aadecode-decode-encoded-as-aaencode.html

<i>Python AADecode </i> 
https://github.com/Zanzibar82/plugin.video.streamondemand/blob/bf655c445e77be57ef4ece84f11b5899a41e0939/servers/openload.py
@mervick

**Comment by mervick** [comment]
Hi, I just wrote [aaencoder/aadecoder](https://github.com/mervick/php-aaencoder), you can try it!
